create DATABASE project;
USE project;
CREATE TABLE words (
    id SERIAL PRIMARY KEY, 
    word VARCHAR(450) NOT NULL
);
INSERT INTO words (word) VALUES
    ('2g1c'),
    ('2 girl 1 cup'),
    ('acrotomophilia'),
    ('alabama hot pocket'),
    ('alaskan pipeline'),
    ('anal'),
    ('anus'),
    ('anilingus'),
    ('apeshit'),
    ('arsehole'),
    ('ass'),
    ('asshole'),
    ('assmunch'),
    ('auto erotic'),
    ('autoerotic'),
    ('babeland'),
    ('baby batter'),
    ('baby juice'),
    ('ball gag'),
    ('ball gravy'),
    ('ball kicking'),
    ('ball licking'),
    ('ball sack'),
    ('ball sucking'),
    ('bangbros'),
    ('bangbus'),
    ('bareback'),
    ('barely legal'),
    ('barenaked'),
    ('bastard'),
    ('bastardo'),
    ('bastinado'),
    ('bbw'),
    ('bdsm'),
    ('beaner'),
    ('beaners'),
    ('beaver cleaver'),
    ('beaver lips'),
    ('beastiality'),
    ('bestiality'),
    ('big black'),
    ('big breats'),
    ('big knockers'),
    ('big tits'),
    ('bimbos'),
    ('birdlock'),
    ('bitch'),
    ('bitches'),
    ('black cock'),
    ('blonde action'),
    ('blonde on blonde action'),
    ('blowjob'),
    ('blow job'),
    ('blow your load'),
    ('blue waffle'),
    ('blumpkin'),
    ('bollocks'),
    ('bondage'),
    ('boner'),
    ('boob'),
    ('boobs'),
    ('booty call'),
    ('brown showers'),
    ('brunette action'),
    ('bukkake'),
    ('bulldyke'),
    ('bullet vibe'),
    ('bullshit'),
    ('bung hole'),
    ('bunghole'),
    ('busty'),
    ('butt'),
    ('buttcheeck'),
    ('butt hole'),
    ('buttcheecks'),
    ('camel toe'),
    ('camgirl'),
    ('camslut'),
    ('camwhore'),
    ('carpetmuncher'),
    ('chocolate rosebuds'),
    ('cialis'),
    ('circlejerk'),
    ('cleveland steamer'),
    ('clit'),
    ('clitoris'),
    ('clover clamps'),
    ('clusterfuck'),
    ('cock'),
    ('cocks'),
    ('coprolagnia'),
    ('coprophilia'),
    ('cornhole'),
    ('coon'),
    ('coons'),
    ('creampie'),
    ('cum'),
    ('cumming'),
    ('cumshot'),
    ('cunnilingus'),
    ('cunt'),
    ('darkie'),
    ('date rape'),
    ('daterape'),
    ('deep throat'),
    ('deepthroat'),
    ('dendrophilia'),
    ('dick'),
    ('dildo'),
    ('dingleberry'),
    ('dingleberries'),
    ('dirty pillow'),
    ('dirty pillows'),
    ('dirty sanchez'),
    ('doggie style'),
    ('doggiestyle'),
	('doggy style'),
    ('doggystyle'),
    ('dos style'),
    ('dolcett'),
    ('domination'),
    ('dominatrix'),
    ('dommes'),
    ('donkey punch'),
    ('double dong'),
    ('double penetration'),
    ('dp action'),
    ('dry hump'),
    ('dvda'),
    ('eat my ass'),
    ('ecchi'),
    ('ejaculation'),
    ('erotic'),
    ('erotism'),
    ('escort'),
    ('eunuch'),
    ('fag'),
    ('faggot'), 
    ('fecal'),
    ('felch'),
    ('female squirting'),
    ('femdom'),
    ('figging'),
    ('fingerbang'),
    ('fingering'),
    ('fisting'),
    ('foot fetish'),
    ('footjob'),
    ('frotting'),
    ('fuck'),
    ('fuck buttons'),
    ('fuckin'),
    ('fucking'),
    ('fucktards'),
    ('fudge pakcer'),
    ('fudgepacker'),
    ('futanari'),
    ('gangbang'),
    ('gang bang'), 
    ('gay sex'),
    ('genitals'),
    ('giant cock'),
    ('girl on'),
    ('girl on top'),
    ('girls gone wild'),
    ('goatcx'),
    ('goatse'),
    ('god damn'),
    ('gokkun'),
    ('golden shower'),
    ('goodpoop'),
    ('goo girl'),
    ('goregasm'),
    ('grope'),
    ('group sex'),
    ('g-spot'),
    ('guro'),
    ('hand job'),
    ('handjob'),
    ('hard core'), 
    ('hardcore'),
    ('hentai'),
    ('homoerotic'),
    ('honkey'),
    ('hooker'),
    ('hooker'),
    ('horny'),
    ('hot carl'),
    ('hot chick'),
    ('how to kill'),
    ('how to murder'),
    ('huge fat'),
    ('humping'),
    ('incest'),
    ('intercourse'),
    ('jack off'),
    ('jail bait'),
    ('jailbait'),
    ('jelly donut'),
    ('jerk off'),
    ('jigaboo'),
    ('jiggaboo'),
    ('jiggerboo'),
    ('jizz'),
    ('jugas'),
    ('kike'),
    ('kinbaku'),
    ('kinkster'),
    ('kinky'),
    ('knobbing'),
    ('leather resistant'),
    ('leather straight jacket'),
    ('lemon party'),
    ('livesex'),
    ('lolita'),
    ('lovemaking'),
    ('make me cum'),
    ('male squirting'),
    ('masturbate'),
    ('masturbating'),
    ('masturbation'),
    ('menage a trois'),
    ('milf'),
    ('missionary position'),
    ('mong'),
    ('motherfucker'),
    ('mound of venus'),
    ('mr hands'),
    ('muff diver'),
    ('muffdiving'),
    ('nambla'),
    ('nawashi'),
    ('nergo'),
    ('neonazi'),
    ('nigga'),
    ('nigger'),
    ('nig nog'),
    ('nimphomaia'),
    ('nipple'),
    ('nipples'),
    ('nsfw'),
    ('nsfw images'),
    ('nude'),
    ('nudity'),
    ('nutten'),
    ('nympho'),
    ('nymphomania'),
    ('octopusssy'),
    ('omorashi'),
    ('one cup two girls'),
    ('one guy one jar'),
    ('orgasm'),
    ('orgy'),
    ('paedophile'),
    ('paki'),
    ('panties'),
    ('panty'),
    ('pedobear'),
    ('pedophile'),
    ('pegging'),
    ('penis'),
    ('phone sex'),
    ('piece of shit'),
    ('pikey'),
    ('pissing'),
    ('piss pig'),
    ('playboy'),
    ('pleasure chest'),
    ('pole smoker'),
    ('ponyplay'),
    ('poof'),
    ('poon'),
    ('poontang'),
    ('punay'),
    ('poop chute'),
    ('poopchute'),
    ('porn'),
    ('porno'),
    ('pornography'),
    ('prince albert piercing'),
    ('pthc'),
    ('pubes'),
    ('pussy'),
    ('queaf'),
    ('queef'),
    ('quim'),
    ('raghead'),
    ('raging boner'),
    ('rape'),
    ('raping'),
    ('rapist'),
    ('rectum'),
    ('reverse cowgirl'),
    ('rimjob'),
    ('rimming'),
    ('rosy palm'),
    ('rosy palm and her 5 sisters'),
    ('rusty trombone'),
    ('sadism'),
    ('santorum'),
    ('scat'),
    ('schlong'),
    ('scissoring'),
    ('semen'),
    ('sex'),
    ('sexcam'),
    ('sexo'),
    ('sexy'),
    ('sexual'),
	('sexually'),
    ('sexuality'),
    ('shaved beaver'),
    ('shaved pussy'),
    ('shemale'),
    ('shibari'),
    ('shit'),
    ('shitblimp'),
    ('shitty'),
    ('shota'),
    ('shrimping'),
    ('skeet'),
    ('slanteye'),
    ('slut'),
    ('s&m'),
    ('smut'),
    ('snatch'),
	('snowballing'),
    ('sodomize'),
    ('sodomy'),
    ('spastic'),
    ('spic'),
    ('sploge'),
    ('sploge moose'),
    ('spooge'), 
    ('spread legs'),
    ('spunk'),
    ('strap on'),
    ('strapon'),
    ('strappado'),
    ('strip club'),
    ('style doggy'),
    ('suck'),
    ('sucks'),
    ('suicide girls'), 
    ('sultry women'),
    ('swastika'),
    ('swinger'),
    ('tainted love'),
    ('taste my'),
    ('tea bagging'),
	('threesome'),
    ('throating'),
    ('thumbzilla'),
    ('tied up'),
    ('tight white'),
    ('tit'),
	('tits'),
    ('titties'),
    ('titty'),
    ('tongue in a'),
    ('topless'),
	('tosser'),
    ('towelhead'),
    ('tranny'),
    ('tribadism'),
    ('tub gurl'),
    ('tub girl'),
	('tubgirl'),
    ('tushy'),
    ('twat'),
    ('twink'),
    ('twinkie'),
	('two girls one cup'),
    ('undressing'),
    ('upskirt'),
    ('uretha play'),
    ('urophilia'),
    ('vagina'),
	('venus mound'),
    ('vaigra'),
    ('vbrator'),
    ('voilet wand'),
    ('varareephilia'),
	('voyeur'),
    ('voyeurweb'),
    ('vouyer'),
    ('vulva'),
    ('wank'),
    ('wetback'),
	('wet dream'),
    ('white power'),
    ('whore'),
    ('worldsex'),
    ('wrapping men'),
	('wrinkled starfish'),
    ('xx'),
    ('xxx'),
    ('yaoj'),
    ('yellow showers'),
    ('yiffy'),
	('zoophilia'),
    ('🖕');
